version: '3'

services:
  mongo_db:
    container_name: mongodb
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    ports:
      - "27017:27017"

  info:
    build:
      context: ./info
    ports:
      - "3003:3003"
    depends_on:
      - mongo_db

  random:
    build:
      context: ./random
    ports:
      - "3002:3002"
    depends_on:
      - mymovies
      - info

  movies:
    build:
      context: ./movies
    ports:
      - "3000:3000"
    depends_on:
      - random

  mymovies:
    build:
      context: ./mymovies
    ports:
      - "3001:3001"
    depends_on:
      - mongo_db
